project_id = "hsjwzymmyfmjexwdezoa"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.identify-product]
    verify_jwt = false
  [functions.review-product]
    verify_jwt = false
